name: 07 - ControlError

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Run a one-line script
        run: echo "Hello, world!"
      
      - name: Run a error
        run: echo "Hello, world!"

      - name: Run a multi-line script
        run: |
          echo "Add other actions to build"
          echo "test, and deploy your project."
          
      - name: Run after error
        if: ${{ failure() }}
        run: |
          echo "Tratar o erro!"
