name: "08 - MergePr"

on:
  workflow_dispatch:
    inputs:
      pr-id:
        required: true
        type: string
 
jobs:
  automerge:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/github-script@v5
        env:
          pull_request_number: ${{ github.event.inputs.pr-id }}
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: ${{env.pull_request_number}},
              event: 'APPROVE'
            })
            
            github.rest.pulls.merge({
              pull_number: ${{env.pull_request_number}}
            })
            
          github-token: ${{secrets.WRITE_TOKEN}}
