name: 10-CreateBranch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create report file
        run: date +%s > report.txt
        
      - name: Create Branch
        run: |
          echo "Create Branch"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b features/teste-01
        shell: pwsh
      
      - name: Create file and push
        run: |
          echo "Create Files and Push"
          date +%s > report.txt
          git add .
          git commit -m "Add file"
          git push origin featues/teste-01
        shell: pwsh
